### PR TITLE
Fix wrong variable name

### PR DESCRIPTION
**Pull request by mllemango**
### WHY are these changes introduced?
Wrong variable in place, caught by @tanema !
image

### WHAT is this pull request doing?
Changing the variable in the message from a boolean value to the feature name.

### CODE REVIEW

**Comment by andyw8** [comment]
Should there have been a test to catch this?

**Comment by mllemango** [comment]
The current tests only check that the feature was properly enabled/disabled, does not check the output message

**Comment by mllemango** [comment]
> Should there have been a test to catch this?

The current tests only check that the feature was properly enabled/disabled, does not check the output message

**Comment by paulomarg** [comment]
> The current tests only check that the feature was properly enabled/disabled, does not check the output message

It should be fairly easy to capture the output in the test by making the context `expect` it.

**Comment by mllemango** [comment]
@paulomarg Updated the tests to check the output! Super new to writing tests for the CLI, any input would be much appreciated 😄

**Review by paulomarg — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
