### PR TITLE
Move .github/LICENSE.md to LICENSE.md

### PR DESCRIPTION
**Pull request by PaulNewton**
License is in .github/LICENSE.md and not the root directory
So not detected by Githubs license summary. 
Nor is it properly linked to with the shield.io license badge in [README.md Line 1](https://github.com/Shopify/shopify-app-cli/blob/master/README.md)

See https://help.github.com/en/articles/licensing-a-repository
https://help.github.com/en/articles/adding-a-license-to-a-repository

### CODE REVIEW

**Comment by katiedavis** [comment]
Thanks @PaulNewton! Please sign the CLA.

**Comment by PaulNewton** [comment]
CLA signed using same email as used in github, not sure how to rerun it?

**Comment by katiedavis** [comment]
Done. Go ahead and merge once Travis passes:)

**Comment by PaulNewton** [comment]
Thanks, for future reference is there a way for me to get notified when travis finally passes in someone else repo?

**Comment by katiedavis** [comment]
@PaulNewton Unfortunately, I couldn't find a way to get notified. Your PR was hanging for a really long time (totally unrelated to moving an MD file) so I admin merged it to see if I could figure out what was happening with the builds. I'll look through the Travis settings to see if I can get third party notifications set up for all you folks :) Thank you again!

**Pull request merged**
