### PR TITLE
Updating CLI Kit/UI vendor code and restore update-deps

### PR DESCRIPTION
**Pull request by paulomarg**
### WHY are these changes introduced?

The CLI UI and Kit repos were updated so they work properly on Windows terminals.

### WHAT is this pull request doing?

This PR pulls in those changes from the upstream repos.

### CODE REVIEW

**Comment by tanema** [comment]
it seems like this broke everything. Did you use the rake task to update it?

**Comment by paulomarg** [comment]
> it seems like this broke everything. Did you use the rake task to update it?

Yes, the new CLI UI code is not compatible with Ruby 2.4 so the tests fail rather spectacularly. I'm in the process of updating Travis to not run 2.4 any more and fix a bunch of 2.7 warnings. I'll then rebase this branch from master and hopefully it will pass.

**Comment by tanema** [comment]
Are you going to bring back the `update_deps` bin?

**Comment by paulomarg** [comment]
Yes, I am planning on doing that.

**Comment by paulomarg** [comment]
@tanema I restored the `update-deps` script - in a separate location so it doesn't delete itself when it updates the deps - and ran it. Once we merge https://github.com/Shopify/shopify-app-cli/pull/804 I will rebase this and it should be good to go!

**Pull request merged**
