### PR TITLE
Revert Spring change to avoid breaking Windows

### PR DESCRIPTION
**Pull request by andyw8**
### WHY are these changes introduced?

Fixes #0000 

### Update checklist

- [ ] I've added a CHANGELOG entry for this PR (if the change is public-facing)

### CODE REVIEW

**Review by mkevinosullivan — COMMENTED** [review]
Will the `|| true` pattern work on Windows?

**Comment by paulomarg** [comment]
> Will the `|| true` pattern work on Windows?

As far as I know, `||` is valid `cmd` syntax but `true` isn't - would `... || exit 0` work?

**Comment by andyw8** [comment]
@paulomarg sadly not, it causes the shell to exit

**Comment by paulomarg** [comment]
We could try just running a simple command that works as a noop, like an echo to the void:

```
<command> || ECHO 'nothingness'>NUL
```

I don't think an empty echo would work here - if memory serves, it toggles a flag if there is no text.

**Comment by andyw8** [comment]
That seems to still result in a non-zero exit status:

Screen Shot 2021-01-18 at 3 28 18 PM

**Comment by paulomarg** [comment]
Interesting, `echo` in Windows doesn't count as a command so it fails to update `%ERRORLEVEL%`, :til:.

What about this?
Screen Shot 2021-01-18 at 3 48 51 PM

**Comment by tanema** [comment]
What exactly is causing the issue? Is it that spring does not exist? Should we just check if spring exists first instead of making something work cross platform?

**Comment by paulomarg** [comment]
> What exactly is causing the issue? Is it that spring does not exist? Should we just check if spring exists first instead of making something work cross platform?

That's a fair point. We do have a method that checks whether something is in the path (for Windows that means something like `something.EXE` exists somewhere in the path) - we could easily extend / copy that call to check a specific path.

That said, we'd still run into issues if `spring stop` actually fails, and if I'm not mistaken we're currently aborting the entire command if something fails - would it make sense to have that raise something so that we can simply catch it and move on?

**Comment by andyw8** [comment]
I'm checking with the cli-kit team to in case there's anything already built-in to handle this kind of task.

**Comment by andyw8** [comment]
Looking at this again, I don't think the `spring stop` is needed at all as we pass the `--skip-spring` flag (#447). I'll close this and open a separate PR to remove that.

**Comment by andyw8** [comment]
Probably not needed any more, but there's `System#which`:

https://github.com/Shopify/cli-kit/blob/136cbd7aceabb9804cfae995aa795df7c713d3bb/lib/cli/kit/system.rb#L224-L234

**Pull request closed without merging**
