### PR TITLE
Light proofread of design doc

### PR DESCRIPTION
**Pull request by christopherclunas**
### WHY are these changes introduced?

Light proofread to fix some typos etc in the doc

### WHAT is this pull request doing?

Suggested fixes and very minor text tweaks

### CODE REVIEW

**Comment by christopherclunas** [comment]
😬 unfortunately there's a build error here that i'm not sure how to address...

**Comment by christopherclunas** [comment]
Looks like I might need to sign into and Activate the Travis CI integration.  Is that right? (Don't want to do it if it's a risk.)

**Comment by katiedavis** [comment]
@christopherclunas looks like something is up with our travis config! I'm going to sort it out rn.

**Comment by katiedavis** [comment]
@christopherclunas if you rebase you should be able to to merge now :)

**Pull request merged**
