### PR TITLE
chore: Update AssemblyScript to v0.14.0

### PR DESCRIPTION
**Pull request by saulecabrera**
### WHY are these changes introduced?

Closes https://github.com/Shopify/script-service/issues/2117

### WHAT is this pull request doing?

Update AssemblyScript to v0.14.0

### Tophat

Checked that everyting works by creating a script and running the tests

### CODE REVIEW

**Review by mkevinosullivan — APPROVED** [review]

**Review by andrewhassan — APPROVED** [review]

**Comment by saulecabrera** [comment]
Hey @mkevinosullivan is it safe to merge given the shipit warning above? I guess the pipeline it's backlogged just because we haven't created a release?

**Comment by mkevinosullivan** [comment]
Hi Saúl, to which shipit warning are you referring?

**Comment by saulecabrera** [comment]
To this one

Screen Shot 2020-10-21 at 1 55 58 PM

**Comment by andyw8** [comment]
@saulecabrera I think that only shows it you have the Ship Chrome extension (I forget its name).

**Comment by paulomarg** [comment]
Shipit doesn't deploy this project automatically, so it's OK to merge your changes even though it's backlogged - that just means a release is due 🙂

**Comment by saulecabrera** [comment]
Thanks!

**Pull request merged**
