### PR TITLE
Fix broken code of conduct link in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by javiguajardo**
### WHY are these changes introduced?
The link to the `code of conduct README` was not correctly linked in the `CONTRIBUTING.md` file.

### WHAT is this pull request doing?
This change correctly links the `code of conduct README`.

### CODE REVIEW

**Comment by javiguajardo** [comment]
I've already signed the CLA, but the build keeps failing...

**Comment by paulomarg** [comment]
Hi @javiguajardo, it seems you are counted as a participant twice (@javiguajardo and @javierguajardo). Considering the PR belongs to the first handle, have you maybe signed the CLA with the second one?

**Comment by javiguajardo** [comment]
> Hi @javiguajardo, it seems you are counted as a participant twice (@javiguajardo and @javierguajardo). Considering the PR belongs to the first handle, have you maybe signed the CLA with the second one?

Hi @paulomarg aaah yes, my mistake. I pushed with my other account 🙈 . It's fixed now :)

**Comment by paulomarg** [comment]
Thank you for this fix @javiguajardo!

**Pull request merged**
